### ISSUE TITLE
Everyplay is crashing on Android N

### ISSUE THREAD

**Issue by mihailogazda** [Everyplay/everyplay-unity-sdk#11]
Hey,

We are experiencing issues due to new security model with NDK in Android N.

Basically the non-white-listed so files like libcutils, libbinder and other are now inaccessible dynamically and have to be linked statically.

Android N documenation:
https://developer.android.com/preview/behavior-changes.html#ndk

The game crashes occasionally after the Everyplay initialization. 
Sometimes user will get this popup, sometimes not. 

Issue screenshot:
http://imgur.com/a/o5sKf

When built with 24 target and 24.0.1 tools the crashes go away, but it does not work either, we never get valid ready callbacks.

From all I see files that need to be linked against are:
libbacktrace.so
libbase.so
libbinder.so
libc++.so
libcrypto.so
libcutils.so
libunwind.so
libutils.so

Best,

**Comment by paugit** [comment]
We are working hard to get Android N recording working. Meanwhile, please download latest Unity Everyplay 2120-1540 - Sep 12th 2016 release. It temporarily disables recording with Android N devices so it does not cause a crash.

**Comment by yaroslavubisoft** [comment]
Hello, we upgraded the plugin to version 2130-1550 but it's still broken on Android N.

Getting this adb log upon initializing Everyplay:
Couldn't load libeveryplay.so: java.lang.UnsatisfiedLinkError: dlopen failed: library "libbinder.so" not found

The app doesn't crash but EveryplayReadyForRecording is always fired with the value set to "false"

**Comment by JustinFincher** [comment]
Hi, I got the same thing with version 2130-1550 on Android N, `ReadyForRecording` value is always return `false`, which makes Google Pixel Phone not able to record. Any news on this?

**Comment by ullatussimo** [comment]
Hello,

Just a quick update here, our next SDK release will address this issue.
Our Android team has worked hard in making our SDK fully compliant with the Android N requirements.

We are still doing the final tweaks and running tests, but the next release should be out really soon.

Thanks for your understanding.

Cheers,
Simo

**Comment by fdonmez** [comment]
Hello,
Is there any update for thisproblem? 
Eveeryplay was working but 2 days ago, it stopped working. I tried t re-install Unity & Android SDK & Everyplay but still not working and I am getting the error below : 
02-15 22:06:44.070 27550 27564 E Everyplay: com.everyplay.Everyplay.c.u() (line:-1) :: Couldn't load libeveryplay.so: java.lang.UnsatisfiedLinkError: dlopen failed: library "libbinder.so" not found

**Comment by rebbTRSi** [comment]
A possible fix (Everyplay 2140-1561) is now be available on the Asset Store. If it does not fix the issue, please re-open this issue.
