### ISSUE TITLE
State of Everyplay

### ISSUE THREAD

**Issue by mihailogazda** [Everyplay/everyplay-unity-sdk#12]
Hey Everyplay,

After 8 months of no updates I'm wondering is this product going to be discontinued in the future?

If not when can the next release cycle be expected?

Best,

**Comment by paugit** [comment]
Unity Everyplay 2120-1540 - Sep 12th 2016 has been released. Another release with Android N support should happen pretty soon too.

**Comment by mihailogazda** [comment]
Thanks guys, will try!
