### ISSUE TITLE
Doesn't build on platform Windows Store

### ISSUE THREAD

**Issue by qbit86** [Everyplay/everyplay-unity-sdk#15]
Assets\Plugins\Everyplay\Scripts\EveryplayRecButtons.cs(397,78): error CS1928: 'EveryplayRecButtons.Button' does not contain a definition for 'GetTypeInfo' and the best extension method overload 'System.Reflection.IntrospectionExtensions.GetTypeInfo(System.Type)' has some invalid arguments

Should be:

```
#if NETFX_CORE
using System.Reflection;
#endif
```

```
#if NETFX_CORE
        isToggleButton = typeof(ToggleButton).GetTypeInfo().IsAssignableFrom(button.GetType().GetTypeInfo());
                                                                                   ^^^^^^^^^^
#else
        isToggleButton = typeof(ToggleButton).IsAssignableFrom(button.GetType());
#endif
```

**Comment by paugit** [comment]
Thanks. We will fix this to the next release soon.

**Comment by bloomk** [comment]
This is STILL not fixed...

**Comment by paugit** [comment]
Doh, really sorry about. Thank you for the reminder.

**Comment by bloomk** [comment]
any idea when this will be fixed?

**Comment by paugit** [comment]
New release should be available some time next month.

**Comment by bloomk** [comment]
is there a workaround?

**Comment by CenekStrichel** [comment]
+1 same problem, no solution. It looks that I have to remove Everyplay for Windows build.

**Comment by paugit** [comment]
EveryplayRecButtons is now ifdeffed out for Windows platform in the latest (Everyplay 2140-1561) Asset Store release.
