### ISSUE TITLE
UI hidden during gameplay but appears during replay

### ISSUE THREAD

**Issue by yrmike** [Everyplay/everyplay-unity-sdk#16]
Thanks for the last update, everything works great except for one thing: I've set GameObjects on the EveryplayHudCamera layer and configured the cameras as explained in the doc.
It works perfectly on Android and most of iOS phones but on several devices it does the opposite: the UI is hidden during gameplay but it's showing up in the replay!

We've experienced the bug on iPhone 5, iPhone 5c.

Thanks for your help!

**Comment by paugit** [comment]
Please use Hotfix 2 from this thread https://forum.unity3d.com/threads/everyplay-sdk-popup-says-build-has-expired.386976/ until new release is out.

**Comment by paugit** [comment]
Should be fixed in latest sdk.
