### ISSUE TITLE
Everyplay build failed on ios

### ISSUE THREAD

**Issue by aholla** [Everyplay/everyplay-unity-sdk#19]
I cant get my ios build to work. Unity 5.4.0. Xcode 7.3.1. Everyplay Release 2121-1540.

`UriFormatException: Invalid URI: The format of the URI could not be determined: Bin/xcode/.
System.Uri..ctor (System.String uriString, Boolean dontEscape)
System.Uri..ctor (System.String uriString)
Everyplay.XCodeEditor.XCProject.AddFile (System.String filePath, Everyplay.XCodeEditor.PBXGroup parent, System.String tree, Boolean createBuildFiles, Boolean weak) (at Assets/Editor/Everyplay/XCodeEditor/XCProject.cs:399)
Everyplay.XCodeEditor.XCProject.ApplyMod (Everyplay.XCodeEditor.XCMod mod) (at Assets/Editor/Everyplay/XCodeEditor/XCProject.cs:684)
Everyplay.XCodeEditor.XCProject.ApplyMod (System.String rootPath, System.String pbxmod) (at Assets/Editor/Everyplay/XCodeEditor/XCProject.cs:634)
EveryplayPostprocessor.ProcessXCodeProject (System.String path) (at Assets/Editor/Everyplay/Scripts/EveryplayPostprocessor.cs:240)
EveryplayPostprocessor.PostProcessBuild_iOS (System.String path, System.String clientId) (at Assets/Editor/Everyplay/Scripts/EveryplayPostprocessor.cs:136)
EveryplayPostprocessor.OnPostProcessBuild (BuildTarget target, System.String path) (at Assets/Editor/Everyplay/Scripts/EveryplayPostprocessor.cs:65)
UnityEditor.HostView:OnGUI()
`

**Comment by aholla** [comment]
So to answer my own issue. The bug it seems is that you have to have you xcode project is the root folder of your unity project.

I do not think the location of your xcode project should be a issue.

**Comment by paugit** [comment]
There should be a workaround for this in the latest sdk.
