### ISSUE TITLE
If can record local music sound  in android?

### ISSUE THREAD

**Issue by zhaoqingqing** [Everyplay/everyplay-unity-sdk#20]
in my game  select mobile local music to play，when record finish ,the movie  no sounds.

**my code**

in unity code

```c#
AndroidJavaClass mPlugin = new AndroidJavaClass("com.xxx.AudioViewActivity");

mPlugin.CallStatic("LocalPlayAudio");

Everyplay.StartRecording();
```

java android native code

```java
private MediaPlayer mediaPlayer;

void LocalPlayAudio(){
         mediaPlayer.setDataSource(pUrl);
	mediaPlayer.start();
}

```

**Comment by ullatussimo** [comment]
Hello zhaoqingqing,

Unfortunately audio played through the MediaPlayer API is not currently properly captured by our SDK. We are investigating a solution for this issue.

In the meantime, I would suggest playing the native audio through the AudioTrack API instead.

Hope this helps.

Cheers,
Simo

**Comment by breaya** [comment]
@ullatussimo hello, I am doing the same work now. How is it going? Thanks.

**Comment by zhaoqingqing** [comment]
@breaya i use www to load music file  in android to resolve it . but in ios www can not have special path.

this my note: http://www.cnblogs.com/zhaoqingqing/p/6064841.html

**Comment by paugit** [comment]
SoundPool and Mediaplayer API are not supported by Everyplay. Closing.
