### ISSUE TITLE
First time open crash on Huawei honor devices.

### ISSUE THREAD

**Issue by funyuto** [Everyplay/everyplay-unity-sdk#23]
Issues on Huawei devices(Tested: Honor 5C,P8).
When game first time open(at this time have not any code refrence EveryPlay code,such as:"Everyplay.IsReadyForRecording()") -- game crash!but on second entry game works well and no everyplay suppored. 

I create a empty project only import everyplay plugin in Unity for confirm is not my game code problem at last the problem happend as same. 

Useful Crash Info:
`02-13 18:52:27.102: I/Everyplay(29465): Everyplay SDK build: 1550
02-13 18:52:27.105: E/linker(29465): readlink('/proc/self/fd/37') failed: Permission denied [fd=37]
02-13 18:52:27.106: E/linker(29465): warning: unable to get realpath for the library "/data/app/com.xxxxx.test-1/lib/arm/libeveryplay.so". Will use given name.
02-13 18:52:27.114: I/Everyplay(29465): JNI_OnLoad done
02-13 18:52:27.152: I/VideoCapabilities(29465): Unsupported profile 16384 for video/mp4v-es
02-13 18:52:27.152: I/VideoCapabilities(29465): Unsupported profile 16384 for video/mp4v-es
02-13 18:52:27.179: I/VideoCapabilities(29465): Unsupported profile 4 for video/mp4v-es
02-13 18:52:27.181: I/Everyplay(29465): com.everyplay.Everyplay.encoding.a.b() (line:-1) :: Multiple video codecs found for video/avc: [OMX.IMG.TOPAZ.VIDEO.Encoder, OMX.google.h264.encoder]
02-13 18:52:27.184: I/Everyplay(29465): com.everyplay.Everyplay.encoding.a.b() (line:-1) :: Multiple video codecs found for video/mp4v-es: [OMX.IMG.TOPAZ.VIDEO.Encoder, OMX.google.mpeg4.encoder]
02-13 18:52:27.184: I/VideoCapabilities(29465): Unsupported profile 16384 for video/mp4v-es
02-13 18:52:27.184: I/VideoCapabilities(29465): Unsupported profile 16384 for video/mp4v-es
02-13 18:52:27.185: I/VideoCapabilities(29465): Unsupported profile 4 for video/mp4v-es
02-13 18:52:27.186: I/Everyplay(29465): com.everyplay.Everyplay.encoding.a.b() (line:-1) :: Codec query took 56 ms
02-13 18:52:27.397: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:27.550: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:27.673: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:27.673: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:27.717: I/AudioManager(29465): requestAudioFocus() status : 1
02-13 18:52:27.717: I/AudioManager(29465): requestAudioFocus() apk    : com.xxxxx.test
02-13 18:52:28.011: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:28.011: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:28.109: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:29.855: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:30.029: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:31.492: I/System(29465): core_booster, getBoosterConfig = false
02-13 18:52:33.313: I/Choreographer(29465): Skipped 36 frames!  The application may be doing too much work on its main thread.
02-13 18:52:33.345: E/lowmemorykiller(309): Error writing /proc/29465/oom_score_adj; errno=22

`
I tested is should not about that Permission problem because I tried give the permission on phone android app manager at first time. Still crash! 

Unity version: 5.5.0p4
Android version:6.0
Everyplay Enable early initalizer setting option is Enable

**Comment by LW1359** [comment]
Me too, first time open crash on HUAWEI device

**Comment by paugit** [comment]
A new Everyplay release (2150-1570) is available and it should fix the crash issue. Unfortunately we had to totally disable Huawei Kirin based devices. We will re-enable the recording support in a future release if we get the recording working.
