### ISSUE TITLE
ThumbnailReadyAtTextureIdDelegate does not exist

### ISSUE THREAD

**Issue by tucano** [Everyplay/everyplay-unity-sdk#24]
Hello in Unity 5.5.0f3 I get:

error CS0426: 

The nested type `ThumbnailReadyAtTextureIdDelegate' does not exist in the type `Everyplay'

Affected method:

`
public event Everyplay.ThumbnailReadyAtTextureIdDelegate ThumbnailReadyAtTextureId
    {
        add
        {
            Everyplay.ThumbnailReadyAtTextureId += value;
        }
        remove
        {
            Everyplay.ThumbnailReadyAtTextureId -= value;
        }
    }
`

**Comment by tucano** [comment]
I have fixed removing EveryplayLegacy.cs from project

**Comment by paugit** [comment]
Yes, that is the best fix for now. EveryplayLegacy.cs is really removed from our codebase however it accidentally appeared in the previous release. A new package will be uploaded shortly.

**Comment by paugit** [comment]
A workaround should now be available on the Asset Store. If it does not fix the issue, please re-open this issue.
