### ISSUE TITLE
Use gradle build require Android ndk?

### ISSUE THREAD

**Issue by coolguji** [Everyplay/everyplay-unity-sdk#25]
Both my PC and Unity have no Android NDK.
If I use File -> Build Settings -> Build to build an Android apk, It can build successful.
But if I use Unity to export an android project and use gradle to build an android apk. It got an error in "everyplay_plugins_lib\build.gradle" line32.
I see the getNdkDir function in build.gradle and it really use ndk to build.
So I just very confused that why use unity "File -> Build Settings -> Build" didn't need android ndk? And the gradle build need the ndk?

**Comment by LW1359** [comment]
:) me too

**Comment by paugit** [comment]
Me too :( We will release a fix for this asap (this week).

**Comment by paugit** [comment]
[ep-gradle-fix.zip](https://github.com/Everyplay/everyplay-unity-sdk/files/804087/ep-gradle-fix.zip)

Please test re-build with the provided files. Build.gradle should go into Plugins/Android/everyplay and EveryplayPostprocessor.cs should go into Editor/Everyplay/Scripts. I am assuming you are using Unity 5.5. If not, we need something else to fix this.

**Comment by paugit** [comment]
Please test re-build with the provided files. Build.gradle should go into Plugins/Android/everyplay and EveryplayPostprocessor.cs should go into Editor/Everyplay/Scripts. I am assuming you are using Unity 5.5. If not, we need something else to fix this.

[ep-gradle-fix2.zip](https://github.com/Everyplay/everyplay-unity-sdk/files/806761/ep-gradle-fix2.zip)

**Comment by paugit** [comment]
A workaround should now be available on the Asset Store. If it does not fix the issue, please re-open this issue.
