### ISSUE TITLE
Build APK error

### ISSUE THREAD

**Issue by LW1359** [Everyplay/everyplay-unity-sdk#26]
**\client\project\android\everyplay\jni: No such file or directory.  Stop.
:everyplay:ndkBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':everyplay:ndkBuild'.
> Process 'command 'C:\Users\hasee\android-ndk-r10e/ndk-build.cmd'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

-------------------------------------------------------------------------------------------------------------------
The above is error information in cmd .
Please help me  solve the issue.
Thanks!

**Comment by paugit** [comment]
Please try if fix in this https://github.com/Everyplay/everyplay-unity-sdk/issues/25 issue helps.

**Comment by paugit** [comment]
A possible fix (Everyplay 2140-1561) is now be available on the Asset Store. If it does not fix the issue, please re-open this issue.
