### ISSUE TITLE
xcode crash when trying to share using everyplay

### ISSUE THREAD

**Issue by sscmikey** [Everyplay/everyplay-unity-sdk#27]
can someone help me with this issue? This is the error log i get: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIPopoverController initWithContentViewController:] called when not running under UIUserInterfaceIdiomPad.

This is the line what causes it inside main.mm UIApplicationMain(argc, argv, nil, [NSString stringWithUTF8String:AppControllerClassName]);

**Comment by paugit** [comment]
Could you provide your XCode version, Everyplay version, test device model and iOS version?

**Comment by sscmikey** [comment]
I already have

**Comment by sscmikey** [comment]
This is the previous message 

Hey. I am using unity 5.5.0. I got this error on my iPhone 6 running on iOs 10.2.1

I also have other plugins like soomla for in app purchasing and ad colony for advertisement and of course facebook as well. All works ok appart from the everyplay share button. As only that causes the crash on my phone with provided logs and screenshot.

I was using unity 5.4.2 but i upgraded because there was the same issue as well and i upgraded everyplay plugin too.

Thank you

**Comment by paugit** [comment]
Iteresting since in Everyplay UIPopoverController is never used on iPad and in your exception it sounds that something tries to use it on iPad. Could you try if it happens without the other plugins?

**Comment by sscmikey** [comment]
thank you i will dig into it and see what is causing it. Does everyplay offer pop up to share via facebook, twitter, mail etc or its only via facebook?

**Comment by paugit** [comment]
In Everyplay you can share to Facebook, Twitter and email.
