### ISSUE TITLE
FaceCamRequestRecordingPermission always returns false

### ISSUE THREAD

**Issue by garciaraul85** [Everyplay/everyplay-unity-sdk#28]
I´m using the EveryplayTest prefab in a test I´m doing, I´m registered, I created a project in your webpage, I got the credentials and added them in the settings of everplay inside unity, so when I run the demo in my android device I always get FaceCamRequestRecordingPermission: False
Thanks in advance for your support.

**Comment by rebbTRSi** [comment]
Best practices for using Facecam can be found here: https://developers.everyplay.com/documentation/Everyplay-Live-FaceCam-integration-to-Unity3d-game.md

On Android 6 or newer we are asking live permissions if you denied permissions on Unity startup or disable permission dialog with SkipPermissionsDialog 
on Android manifest.
