### ISSUE TITLE
First install game and run crash on HUAWEI device

### ISSUE THREAD

**Issue by LW1359** [Everyplay/everyplay-unity-sdk#29]
I integrate everyplay in project. And build apk, run game and crash in HUAWEI device.
Of course, only this device have crash issue. I try not enable early initalize and build  ->  run game ,no crash. 
Then , i try enable early initalize and add "try catch" in EveryplayEarlyInitializer script. 

    [RuntimeInitializeOnLoadMethod]
	static void InitializeEveryplayOnStartup()
    {
		try
		{
	    	 EveryplaySettings settings = (EveryplaySettings) Resources.Load("EveryplaySettings");
			 if (settings != null)
	      	 {
	       	    if (settings.earlyInitializerEnabled && settings.IsEnabled && settings.IsValid)
	            {
	               Everyplay.Initialize();        
		  		}
			 }
		}
		catch(System.Exception e) 
		{
			Debug.LogWarning("everyplay initialize fail " + e);
		}
	}

then build -> run game , and crash.
I find the error in Dalvik Debug Monitor. 
The following is  error content :
Fatal signal 11(SIGSEGV), code 2 , fault addr 0xaf4a3678 in tid 7902(UnityMa in)

**Comment by paugit** [comment]
A new Everyplay release (2150-1570) is available and it should fix the crash issue. Unfortunately we had to totally disable Huawei Kirin based devices. We will re-enable the recording support in a future release if we get the recording working.
