### ISSUE TITLE
Android: Crash whilst trying to share/upload video unauthenticated

### ISSUE THREAD

**Issue by acornies** [Everyplay/everyplay-unity-sdk#3]
Using Unity 4.6.1p1, and the latest (Dec 16th 2014) release.

Building to a Nexus 5 (Lollipop 5.0.1) trying to share a video (unauthenticated) causes the game to crash/restart, consequently loosing game video and game state. It happens when trying to login or filling out DOB in the Everyplay dialogue.

**Comment by BoaNeo** [comment]
Any resolution to this?

I have the same problem - Everyplay crashes consistently no matter which of the share buttons (FB, Twitter or Youtube) I press. Nexus 5 Lollipop, Unity 4.6.1p4 

I am using the release from Feb.20th 2015

**Comment by aet** [comment]
Sorry for the delay, we've just released a new build 1950-1300 that comes up with multiple fixes to Android, along graphics performance rewrite. Please let me know if the issues persist and thank you for reporting!
