### ISSUE TITLE
Android Build Failed : "Found plugins with same names and architectures"

### ISSUE THREAD

**Issue by tashfiq103** [Everyplay/everyplay-unity-sdk#30]
Dear Everyplay support team.

Thank you so much for taking the query.

I am having the following issue of "Found plugins with same names and architectures" on the following directory. Can you please tell me the solution to this problem? The following images showing the issue.

![conflict](https://cloud.githubusercontent.com/assets/10606026/25264581/c9174276-2689-11e7-979c-d00c6f55e939.png)

**Comment by tashfiq103** [comment]
[Solved]

That was quick by me to be honest xD . Some of the guy in the unity forum was saying to delete one of the library which is not the best you wanna do.

So the problem was when you import the "Everyplay" package from the "Asset Store", the both "libeveryplay" are selected with "ARMv7" under the "Android" section. So all you need to do is to change that to "x86" at the "libeveryplay" that is under the "Plugin/Everyplay/AndroidDynamicLibraries/x86/libeveryplay".

![solution](https://cloud.githubusercontent.com/assets/10606026/25265042/a0df5bec-268c-11e7-92f3-4f7ecee0b316.png)


That's it, you are all good to go for making your "Android Build" :)

**Comment by tashfiq103** [comment]
Hoping to resolve the issue on the next update of Everyplay.

Thank you so much for the excellent support from the community :)

**Comment by paugit** [comment]
This should be resolved in the latest release (2150-1570). If not, please reopen the issue. You might need to remove the old plugin or at least uncheck/check the Android support in Everyplay settings.
