### ISSUE TITLE
Android build not work and show no error log

### ISSUE THREAD

**Issue by Biodam** [Everyplay/everyplay-unity-sdk#31]
Hello. 

When I build to Android and tested on Nexus 5x and Moto G2 it simply does not work and don't show any log of erros.

The same build on iOS, iPhone 5C, works perfectly.

Any ideas why?

**Comment by rebbTRSi** [comment]
Can you give little bit more information about your build setup and Unity version. Also, a full Android log would be useful.

**Comment by Biodam** [comment]
Of course. Sorry.

I was in a bit of a hurry when wrote it.

I'm using Unity 5.6.1. Building for Nexus 5x Android 7.1.2 and Moto G2 Android 6.

Where I can get the Android log?

(Sorry about my english, I'm from Brazil)

**Comment by rebbTRSi** [comment]
Are you using OSX or Windows? Adb logcat or similar is fine for the logs.

**Comment by paugit** [comment]
Is your Android devices connected to the Internet? On Android Internet is needed for the first time to enable recording on the device. On iOS, Internet is not required.

**Comment by Biodam** [comment]
Yes It has internet, tripled checked it.

Hello. It was my first time creating a log with adb logcat. Hope it helps.
[logcatEveryplayNotWorking.txt](https://github.com/Everyplay/everyplay-unity-sdk/files/1027283/logcatEveryplayNotWorking.txt)

If I have anything more to do to help. Just say it. Thanks for your time trying to help.

**Comment by paugit** [comment]
It seems Everyplay native file is missing from your build. Please try to remove Everyplay totally (Editor/Everyplay and Plugins/Everyplay) and re-import the latest version (2150-1570) from the Asset Store. Please remember to put your client id to the settings after import.

If this does not help, please re-open this issue.
