### ISSUE TITLE
API access for upload

### ISSUE THREAD

**Issue by yosun** [Everyplay/everyplay-unity-sdk#34]
Is there a way to have videos be uploaded automatically right after recording? Or, API access for upload

**Comment by paugit** [comment]
Unfortunately automatic sharing of videos is not possible, as we always require that the end-user initiates the video upload.
Regarding API access, you can monitor the uploading process via the events Everyplay.UploadDidStart, Everyplay.UploadDidProgress, Everyplay.UploadDidComplete.
