### ISSUE TITLE
Not working in Unity5.2.0f X64

### ISSUE THREAD

**Issue by Arshiamidos** [Everyplay/everyplay-unity-sdk#36]
i downloaded package 
dragged Everyplayprefab on hierarcy window 
copy and paste my client id and secret to unity3d

it show `start recording` and `every play` and `send CAM req ` on editor 
BUT
nothing work
NOT EVEN editor 
i googled 
i youtubed
reading doc 100 times
reading sites and manuals 100 times
checked checkbox of prefabs for android initial and ....
not even android device HUAWEI and samsung
is that necesseray a custome unity 3d ?
is that necessary our device have SD card?
can anybody upload sample test ????

**Comment by paugit** [comment]
64 bit Huawei device are currently not supported. Did you have Internet connection enabled for the Samsung device? Internet connection is required when using Everyplay for the first time since we validate the device support from our servers.

**Comment by Arshiamidos** [comment]
thanks for ur feedback @paugit  
but i skiped that problem because it's filtred in my country 
i can now access to Everplay BUT it's not efficent for my user to connect with proxy softwares in android
