### ISSUE TITLE
Unity3D error when building an Android apk

### ISSUE THREAD

**Issue by haythemstiti** [Everyplay/everyplay-unity-sdk#37]
Unity version: 2017.2.0f3 Personal
It works fine with iOS though. I checked if there are *.jar or .aar files that have the same name but didn't find any
![capture](https://user-images.githubusercontent.com/6554171/33854071-abe6f6b6-dec0-11e7-99cb-6e3b48e7544d.PNG)

**Comment by rgngl** [comment]
Hi,

Does this happen only with Everyplay enabled? From the error message it looks like it's caused by a class from another library(`cn.com.wali.basetool.io.a`).

**Comment by haythemstiti** [comment]
Hi,
Thank you for your reply.
It only happens when Everyplay for Android is enabled. It does not occur with iOS. Unfortunately, I can't confirm which plugin is responsible for this. Can you confirm that it's not a class related to an Everyplay's library?

**Comment by rgngl** [comment]
Yes, definitely. That class is not coming from EP. Can you reproduce it with an empty project with just Everyplay in it?

**Comment by haythemstiti** [comment]
Sorry for the late reply.
In fact, the error is caused by another external library. In my case, It's from Android Native plugin. I was able to solve this by deactivating "Enable Camera" in Android Native which apparently made a conflict with camera access of Everyplay.
