### ISSUE TITLE
ld: framework not found EveryplayCore

### ISSUE THREAD

**Issue by smaritem** [Everyplay/everyplay-unity-sdk#38]
Hello dear people,
i get this error when i try to build my ios project. I tried it with unity 5.5.5, 5.6.4 and xcode 8.3, 9 & 9.2. Always the same error.
The sdk folder of ios only contains the Everyplay.bundle & Everyplay.framework, but not EveryplayCore.framework
I need their help, 
thanks

**Comment by paugit** [comment]
Hello. iOS build should exactly contain Everyplay.bundle and Everyplay.framework. There should never be EveryplayCore.framework in iOS build and that file is not even included in Everyplay Unity package. How do create your xcode project (through the build menu, commandline)? Do you have other post processor scripts in your project? If yes, does some of those give any errors? It sounds that the post processor thinks for some reason that you are doing a Mac build even you are doing an iOS build.

**Comment by smaritem** [comment]
Hello, thanks for the reply.
I found these code lines 

       #if UNITY_IPHONE || UNITY_IOS
        platformDependencyList.Add("Everyplay.framework");
        platformDependencyList.Add("Everyplay.bundle");
#else
        platformDependencyList.Add("EveryplayCore.framework");
#endif

in the EveryplayPostprocessor.cs file  under
C:\Users\Public\Documents\Unity Projects\MyGame\Assets\Editor\Everyplay\Scripts

And also under 
C:\Users\Public\Documents\Unity Projects\MyGame\iOSGame\Everyplay
in the "EveryplayUnity.h", you have these lines
<
#import <Foundation/Foundation.h>
#if __has_include(<Everyplay/Everyplay.h>)
#import <Everyplay/Everyplay.h>
#elif __has_include(<EveryplayCore/EveryplayCore.h>)
#define EVERYPLAY_COMPAT_WRAPPER 1
#import <EveryplayCore/EveryplayCore.h>
#endif
>

**Comment by paugit** [comment]
Hello. So are you using the build menu or building from command line? I noticed that Unity sometimes does not define UNITY_IOS correctly when building the project for the first time (when the Library folder does not yet exist). This issue might happen with automated builds that download the project and then immediately build the project. You can probably workaround this issue by putting UNITY_IOS to the scripting define symbols in player settings or building the project twice.

**Comment by smaritem** [comment]
HEllo,
I have it now. I m building from command line. The error come from a pre-parsing utility, which doesn't support conditional includes.
Now the error doesnt show anymore!
Thanks
