### ISSUE TITLE
Final SDK and Android 19

### ISSUE THREAD

**Issue by BigToeProductions** [Everyplay/everyplay-unity-sdk#42]
While the final Everyplay SDK seems to work on later versions of the Android OS, it no longer seems to work on Android 16-19.  Was there a change made where it wouldn't work on that version of the OS, or should I be looking for some other reason?

Thanks

**Comment by voxelbustersold** [comment]
Incase if anyone is looking for screen recording on both iOS and Android along with better frame rates, have a look at  “Cross Platform Replay Kit” -  http://u3d.as/1nN3 available on asset store.
