### ISSUE TITLE
Saving recorded video for upload later

### ISSUE THREAD

**Issue by yosun** [Everyplay/everyplay-unity-sdk#6]
Is there a way to save a recorded video for upload later?

**Comment by collectivemass** [comment]
Yea. You can find the videos usually in Everyplay cache or the default unity Cache folder. Everyplay only stores on play back at a time but you can copy the video out of the cache folder before its shared and then share it later. If you are not going to record any more videos, you can just call the share method when you are ready instead of copying files.

**Comment by ripegooseberry** [comment]
@collectivemass I tried to follow your hint and started looking for the video in Cache folder during playback. 
I found no video in Caches on iOS :( I did find it only on Android (but I really need iOS).
I looked in Application.persistentDataPath, Application.dataPath, Application.temporaryCachePath

Were you able to find the video file in Caches on iOS during playback? If so, in which subfolder? 
Thanks again.

**Comment by collectivemass** [comment]
@ripegooseberry Sorry mate, they might have moved it. Heres the steps I followed to find the video. Im doing it step by step while I check on the latest game we made. 
1) Open xcode
2) in xcode, go to window->devices
3) select your ios device in the devices panel and double click on your game under "Installed Apps". This will then show you a full file listing of whats going on with your game.
4) Now you know where to look, start up your app and do a recording with everyplay.
5) Once you are sure you have a valid recording, double click on your app in the xcode devices panel and look at your file system again. Remember, Everyplay cleans up after itself, so it has to be recent.
6) This time, I found my video in the "tmp" folder. The path was tmp/Everyplay/sesson/<GUID>/screen.mp4.

I think, to get to the tmp folder, you use "Application.temporaryCachePath" but you should be able to get to it no matter what using a little path magic eg "../".

Hope that helps!

**Comment by tuanzi88** [comment]
Hi, what is the video's path in Android device?

**Comment by bhavani0824** [comment]
Hi, how to save the recorded video to the gallery

**Comment by paugit** [comment]
Currently there is no public api to achieve this. Videos are intended to be shared through Everyplay.

**Comment by yosun** [comment]
It is rather a pity - sometimes users are on long plane flights or in areas where uploading is not convenient (slow internet etc) ... would be great if there is a way to access several replays locally instead of only the last one... or if there is a way to access recordings to save them locally persistently

**Comment by Ranttal** [comment]
I am able to save the video locally but the problem i am facing is that it save a video locally only once means the first video after making build, so i want to know to save all the video made by Everyplay.
Here is my code:
  public void SaveVideoInCameraRoll()
    {
		Debug.Log ("Reaching stage 111");
		var root = new DirectoryInfo(Application.persistentDataPath).Parent.FullName;
		Debug.Log ("Reaching stage 222");
        var everyplayDir = root + "/tmp/Everyplay/session/";
		Debug.Log ("Reaching stage 333");
		var files = new DirectoryInfo(everyplayDir).GetFiles("*.mp4", SearchOption.AllDirectories);
		Debug.Log ("Reaching stage 444");
		var videoLocation = "";
        foreach (var file in files)
        {
            videoLocation = file.FullName;
            Debug.Log("Temp Fiele = "+ videoLocation);
        }
        Debug.Log("Fiele length = "+files.Length);

        FileInfo info = new FileInfo(videoLocation);
		if (info == null || info.Exists == false)
			Debug.Log ("File is not exist");
		else
			Debug.Log ("File Exists = ");

        videosave.CopyVideoToCameraRoll(videoLocation);
    }
